Models/ErrorViewModel.cs
namespace UTN_SEU_Cursos.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace UTN_SEU_Cursos.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult index()
        {
            return View("Contacto");
        }
    }
}

Controllers/CursosController.cs
using Microsoft.AspNetCore.Mvc;

namespace UTN_SEU_Cursos.Controllers
{
    public class CursosController : Controller
    {

        public IActionResult index()
        {
            return View("Index");
        }
        public IActionResult online()
        {
            return View("Online");
        }
        public IActionResult streaming()
        {
            return View("Streaming");
        }
        public IActionResult presencial()
        {
            return View("Presencial");
        }

        public IActionResult automotor()
        {
            return View("Automotor");
        }

        public IActionResult motos()
        {
            return View("Motos");
        }

        public IActionResult communityManager()
        {
            return View("communityManager");
        }

        public IActionResult refrigeracion()
        {
            return View("Refrigeracion");
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using UTN_SEU_Cursos.Models;

namespace UTN_SEU_Cursos.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Contact/Contacto.cshtml
<section class="main-container">

        <div class="container">
          <div class="row">

            <!-- main start -->
            <!-- ================ -->
            <div class="main col-lg-8 space-bottom">
              <div class="contact-form">
                <form class="margin-clear">
                  <div class="form-group has-feedback">
                    <label for="name">Nombre*</label>
                    <input type="text" class="form-control" id="name" placeholder="Nombre" required>
                    <i class="fa fa-user form-control-feedback"></i>
                  </div>
                  <div class="form-group has-feedback">
                    <label for="email">Email*</label>
                    <input type="email" class="form-control" id="email" aria-describedby="emailHelperText" placeholder="Ingresa un email" required>
                    <i class="fa fa-envelope form-control-feedback"></i>
                    <small id="emailHelperText" class="form-text text-muted mt-2"></small>
                  </div>
                  <div class="form-group has-feedback">
                    <label for="subject">Asunto*</label>
                    <input type="text" class="form-control" id="subject" placeholder="Asunto" required>
                    <i class="fa fa-navicon form-control-feedback"></i>
                  </div>
                  <div class="form-group has-feedback">
                    <label for="message">Mensaje*</label>
                    <textarea class="form-control" rows="6" id="message" placeholder="Mensaje" required></textarea>
                    <i class="fa fa-pencil form-control-feedback"></i>
                  </div>
                  <input type="submit" value="Enviar" class="submit-button btn btn-default">
                </form>
              </div>
            </div>
            <!-- main end -->

            <!-- sidebar start -->
            <!-- ================ -->
            <aside class="col-lg-3 ml-xl-auto">
              <div class="sidebar">
                <div class="side vertical-divider-left">
                  <div id="logo" class="logo d-flex justify-content-center justify-content-md-start">
                                    <a href="/"><img id="logo_img" src="../images/logos/logo_utn.png" alt="UTN - SEU"></a>
                                </div>
                  <div class="separator-2 mt-20"></div>
                  <ul class="list">
                    <li><i class="fa fa-home pr-10"></i><span>Av. de la Universidad 501
        (2400) San Francisco
        Córdoba - República Argentina</span></li>
                    <li><i class="fa fa-phone pr-10"></i><abbr title="Phone"></abbr> (03564) 435402 / 421147</li>
                    <li><i class="fa fa-envelope pr-10"></i><a href="mailto:capacitacionyoficios@sanfrancisco.utn.edu.ar">capacitacionyoficios@sanfrancisco.utn.edu.ar</a></li>
                  </ul>
                  <ul class="social-links circle small margin-clear clearfix animated-effect-1">
                                                <li class="facebook"><a href="https://www.facebook.com/utnsanfrancisco" target="_blank"><i class="fa fa-facebook"></i></a></li>
                                                <li class="youtube"><a href="https://www.youtube.com/channel/UCw5iNPn6LFC3EAjWWc2Nv0A/featured" target="_blank"><i class="fa fa-youtube"></i></a></li>
                                                <li class="twitter"><a href="https://twitter.com/utnsanfco" target="_blank"><i class="fa fa-twitter"></i></a></li>
                                                <li class="instagram"><a href="https://www.instagram.com/saeutnsanfco/" target="_blank"><i class="fa fa-instagram"></i></a></li>
                  </ul>
                  <div class="separator-2 mt-20 "></div>

                </div>
              </div>
            </aside>
            <!-- sidebar end -->
          </div>
        </div>
      </section>

Views/Cursos/Automotor.cshtml
 <section class="main-container padding-bottom-clear section pv-40 fixed-bg light-translucent-bg background-img-2"">



     <div >
        <div class="container">
          <div class="row ">


            <div class="clearfix"></div><div class="main col-lg-8 pv-40">
              <h1 class="title text-center">Electrónica del Automotor</h1>
              <div class="separator with-icon"><i class="fa fa-car bordered"></i></div>
              <p class="font-cursos">La Dirección de Capacitación y Oficios de la U.T.N. Facultad Regional San Francisco llevará a cabo un curso de capacitación técnica en: “Electrónica del Automotor”, destinado a aquellas personas que necesitan una rápida capacitación laboral, mecánicos, electricistas, personal de mostrador de repuesterías del automotor y para toda persona interesada que sepa el funcionamiento básico de un motor a combustión interna.</p>
              <h3 class="title"><strong>Metodología:</strong></h3>
              <ul class="list-icons font-cursos">
                <li><i class="fa fa-check"></i> Una clase presencial semanal teórico práctica de dos horas y treinta minutos (2 y 1/2).</li>
                <li><i class="fa fa-check"></i> Evaluación a la finalización del módulo.</li>
              </ul>

              <h3 class="title"><strong>Objetivos:</strong></h3>
              <ul class="list-icons font-cursos">
                <li><i class="fa fa-check"></i>Actualizar a mecánicos o interesados en general, en sistemas electrónicos de control de la combustión para evitar la contaminación con un motor modernizado tecnológicamente.</li>
              </ul>

              <h3 class="title"><strong>Temario:</strong></h3>
              <ul class="list-icons font-cursos">
                <li><i class="fa fa-check"></i> Repaso de funcionamiento motor 4 tiempos-Relación de compresión. </li>
                <li><i class="fa fa-check"></i> Electricidad y electrónica básica aplicada al automotor.</li>
                <li><i class="fa fa-check"></i> Practica de circuitos eléctricos.</li>
                <li><i class="fa fa-check"></i> Encendidos electrónicos  de 2º y 3º generación controlados por la E.C.U.</li>
                <li><i class="fa fa-check"></i> Control de gestión del motor: Sistema antipistoneo por control electrónico del avance de chispa.</li>
                <li><i class="fa fa-check"></i> Control de la mezcla estequiometrica por zonda lambda.</li>
                <li><i class="fa fa-check"></i> Inyección de nafta indirecta: Grupo de sensores, funciones de cada uno.</li>
                <li><i class="fa fa-check"></i> Grupo de actuadores: Función de cada uno.</li>
                <li><i class="fa fa-check"></i> Acción de la E.C.U. sobre sensores y actuadores.</li>
                <li><i class="fa fa-check"></i> Funcionamiento eléctrico-electrónico de cada sensor y su control de calidad.</li>
                <li><i class="fa fa-check"></i> Funcionamiento eléctrico de cada actuador y su control de calidad.</li>
                <li><i class="fa fa-check"></i> Control sobre todo el sistema en funcionamiento normal sobre un automóvil.</li>
                <li><i class="fa fa-check"></i> Controles sobre sensores y actuadores sobre el motor en funcionamiento.</li>
                <li><i class="fa fa-check"></i> Análisis sobre tablas de fallas.</li>
                <li><i class="fa fa-check"></i> Inyección de nafta a mezcla pobre o directa.</li>
                <li><i class="fa fa-check"></i> Inyección de gasoil por sistema Common Rail.</li>
              </ul>


              @*<a href="#" class="btn btn-animated btn-default btn-lg">External Link <i class="fa fa-external-link"></i></a>*@
              <hr>

            </div>
            <!-- main end -->

            <!-- sidebar start -->
            <!-- ================ -->
            <aside class="col-lg-4 col-xl-3 ml-xl-auto pv-40">
              <div class="sidebar">
                <div class="block clearfix font-cursos">
                  <h3 class="title">Info</h3>
                  <div class="separator-2"></div>
                  <ul class="list margin-clear">
                    <li><strong>Docente:  </strong> <span class="text-right">Juan Carlos Martínez</span></li>
                    <li><strong>Fecha de inicio:  </strong> <span class="text-right">Martes 15 de marzo de 2022</span></li>
                    <li><strong>Horarios: </strong> <span class="text-right">17:00 a 19:30 Duración: 36 clases - 90 horas reloj. </span></li>
                    <li><strong>Precio: </strong> <span class="text-right">9 cuotas de $ 3900 (descuentos para alumnos UTN y empresas)</span></li>
                    
                  </ul>
                </div>
                
                
                </div>
              </div>
            </aside>
            <!-- sidebar end -->
             </div>
        </div>
      </section>

Views/Cursos/Index.cshtml
<section class="light-gray-bg pv-30 clearfix light-translucent-bg ">
        <div class="container">
          <div class="row justify-content-lg-center">
            <div class="col-lg-8">
              <h2 class="text-center">Cursos <strong>UTN</strong></h2>
              <div class="separator"></div>
              @*<p class="large text-center">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Numquam voluptas facere vero ex tempora saepe perspiciatis ducimus sequi animi.</p>*@
            </div>
          </div>

          <div class="row">

            <div class="col-lg-4">
              <div class="pv-30 ph-20 hc-item-box bordered hc-shadow-2 text-center hc-element-invisible" data-animation-effect="fadeInDownSmall" data-effect-delay="100">

                <h3>STREAMING</h3>
               
                <a href="@Url.Action("streaming", "Cursos")"><i></i>
                   <img src="images/cursos/streaming1140x1410.jpg" /> </a>
              </div>
            </div>    
            

             <div class="col-lg-4">
              <div class="pv-30 ph-20 hc-item-box bordered hc-shadow-2 text-center hc-element-invisible" data-animation-effect="fadeInDownSmall" data-effect-delay="100">

                <h3>PRESENCIAL</h3>
         
                <a href="@Url.Action("presencial", "Cursos")"><i></i>
                   <img src="images/cursos/presencial1140x1410.jpg" /> </a>
              </div>
            </div>


            <div class="col-lg-4">
              <div class="pv-30 ph-20 hc-item-box bordered hc-shadow-2 text-center hc-element-invisible" data-animation-effect="fadeInDownSmall" data-effect-delay="100">

                <h3>ONLINE</h3>
                
                <a href="@Url.Action("online", "Cursos")"><i></i>
                   <img src="images/cursos/online1140x1410.jpg" /> </a>
              </div>
            </div>




          </div> 






          
        </div>
      </section>

Views/Cursos/Motos.cshtml
 <section class="main-container padding-bottom-clear section pv-40 fixed-bg light-translucent-bg background-img-motos">
     <div >
        <div class="container">
          <div class="row ">

            <div class="clearfix"></div><div class="main col-lg-8 pv-40">
              <h1 class="title text-center">Mecánica y Electricidad de motos</h1>
              <div class="separator with-icon"><i class="fa fa-motorcycle bordered"></i></div>
              <p class="font-cursos">La Dirección de Capacitación y Oficios de la U.T.N. Facultad Regional San Francisco llevará a cabo un curso de 
                  capacitación técnica en: “Mecánica y Electricidad de motos”, destinado al público en general interesado en el rubro, con o sin 
                  conocimientos previos.</p>
              <h3 class="title"><strong>Metodología:</strong></h3>
              <ul class="list-icons font-cursos">
                <li><i class="fa fa-check"></i>Una clase presencial semanal teórico práctica de dos horas y treinta minutos (2 y 1/2).</li>
              </ul>

              <h3 class="title"><strong>Objetivos:</strong></h3>
              <ul class="list-icons font-cursos">
                <li><i class="fa fa-check"></i>El alumno debe reconocer las partes, diagnosticar el problema y poder deducir los a seguir para 
                    lograr el buen funcionamiento mecánico y reparar una moto, como así también manejar correctamente las herramientas adecuadas que 
                    posibilitarán el cumplimiento de objetivos.</li>
              </ul>

              <h3 class="title"><strong>Temario:</strong></h3>
              <ul class="list-icons font-cursos">
                <li><i class="fa fa-check"></i> Unidad 1: Motor / Examen</li>
                <li><i class="fa fa-check"></i> Unidad 2: Chasis  / Examen</li>
                <li><i class="fa fa-check"></i> Unidad 3: Electricidad / Examen</li>                
              </ul>


              @*<a href="#" class="btn btn-animated btn-default btn-lg">External Link <i class="fa fa-external-link"></i></a>*@
              <hr>

            </div>
            <!-- main end -->

            <!-- sidebar start -->
            <!-- ================ -->
            <aside class="col-lg-4 col-xl-3 ml-xl-auto pv-40">
              <div class="sidebar">
                <div class="block clearfix font-cursos">
                  <h3 class="title">Info</h3>
                  <div class="separator-2"></div>
                  <ul class="list margin-clear">
                    <li><strong>Docente:  </strong> <span class="text-right">Maximiliano Pampiglione</span></li>
                    <li><strong>Fecha de inicio(1er grupo):  </strong> <span class="text-right">Lunes 9 de mayo de 2022.</span></li>
                    <li><strong>Fecha de inicio (2do grupo):  </strong> <span class="text-right">Miércoles 11 de mayo de 2022.</span></li>
                    <li><strong>Horarios: </strong> <span class="text-right">20:00 a 22:30  Duración: 24 clases - 60 horas reloj. </span></li>
                    <li><strong>Precio: </strong> <span class="text-right">7 cuotas de $ 3900 (descuentos para alumnos UTN y empresas)</span></li>
                    
                  </ul>
                </div>
                
                
                </div>
              </div>
            </aside>
            <!-- sidebar end -->
             </div>
        </div>
      </section>

Views/Cursos/Online.cshtml
<section class="light-gray-bg pv-30 clearfix light-translucent-bg ">
        <div class="container">
          <div class="row justify-content-lg-center">
            <div class="col-lg-8">
              <h2 class="text-center">Cursos <strong>UTN</strong></h2>
              <div class="separator"></div>
              @*<p class="large text-center">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Numquam voluptas facere vero ex tempora saepe perspiciatis ducimus sequi animi.</p>*@
            </div>
          </div>

          <h2 class="mt-4 ">ONLINE </h2>

          <div class="main col-12">
           <div class="filters">
                <ul class="nav nav-pills">
                  <li class="nav-item"><a class="nav-link active" href="#" data-filter="*">TODOS</a></li>
                  <li class="nav-item"><a class="nav-link" href="#" data-filter=".laboral">LABORAL</a></li>
                  <li class="nav-item"><a class="nav-link" href="#" data-filter=".tecnologico">TECNOLÓGICO</a></li>
                  <li class="nav-item"><a class="nav-link" href="#" data-filter=".hab-blandas">HAB. BLANDAS</a></li>
                  <li class="nav-item"><a class="nav-link" href="#" data-filter=".oficio">OFICIO</a></li>
                </ul>
              </div>
          
              <div class="isotope-container row grid-space-10">

            <div class="col-lg-4 col-md-6 isotope-item oficio">
              <div class="pv-30 ph-20 hc-item-box bordered hc-shadow-2 text-center hc-element-invisible " data-animation-effect="fadeInDownSmall" data-effect-delay="100">
                <span class="icon default-bg circle"><i class="fa fa-car"></i></span>
                <h3>Electronica del automotor</h3>
                <div class="separator clearfix"></div>
                <p>Actualizar a mecánicos o interesados en general, en sistemas electrónicos de control de la combustión para evitar la contaminación con un motor modernizado tecnológicamente.</p>
                <a href="@Url.Action("automotor", "Cursos")">Leer mas <i class="pl-1 fa fa-angle-double-right"></i></a>
              </div>
            </div>

            <div class="col-lg-4 col-md-6 isotope-item oficio">
              <div class="pv-30 ph-20 hc-item-box bordered hc-shadow-2 text-center hc-element-invisible" data-animation-effect="fadeInDownSmall" data-effect-delay="200">
                <span class="icon default-bg circle"><i class="fa fa-motorcycle"></i></span>
                <h3>Mecánica y Electricidad de motos</h3>
                <div class="separator clearfix"></div>
                <p>El alumno debe reconocer las partes, diagnosticar el problema y poder deducir los a seguir para 
                    lograr el buen funcionamiento mecánico y reparar una moto, como así también manejar correctamente las herramientas adecuadas que 
                    posibilitarán el cumplimiento de objetivos.</p>
                <a href="@Url.Action("motos", "Cursos")">Leer mas <i class="pl-1 fa fa-angle-double-right"></i></a>
              </div>
            </div>

           <div class="col-lg-4 col-md-6 isotope-item oficio">
              <div class="pv-30 ph-20 hc-item-box bordered hc-shadow-2 text-center hc-element-invisible" data-animation-effect="fadeInDownSmall" data-effect-delay="300">
                <span class="icon default-bg circle"><i class="fa fa fa-snowflake-o"></i></span>
                <h3>Refrigeración y Aire Acondicionado</h3>
                <div class="separator clearfix"></div>
                <p>Lograr a través de la instrucción electromecánica, personal capacitado,  en la reparación y mantenimiento de equipos de frio familiares.</p>
                <a href="@Url.Action("refrigeracion", "Cursos")">Leer mas <i class="pl-1 fa fa-angle-double-right"></i></a>
              </div>
            </div>

         
            </div>
          </div>

           


          
        </div>
</section>

Views/Cursos/Refrigeracion.cshtml
<section class="main-container padding-bottom-clear section pv-40 fixed-bg light-translucent-bg background-img-refrigeracion">
     <div >
        <div class="container">
          <div class="row ">


            <div class="clearfix"></div><div class="main col-lg-8 pv-40">
              <h1 class="title text-center">Refrigeración y Aire Acondicionado</h1>
              <div class="separator with-icon"><i class="fa fa-snowflake bordered"></i></div>
              <p class="font-cursos">La Dirección de Capacitación y Oficios de la U.T.N. Facultad Regional San Francisco llevará a cabo un curso de 
                  capacitación técnica en: “Refrigeración y Aire Acondicionado”, destinado a aquellas personas que necesitan una rápida capacitación 
                  laboral, que responda a las necesidades actuales del mercado, asegurándose una formación.</p>
              <h3 class="title"><strong>Metodología:</strong></h3>
              <ul class="list-icons font-cursos">
                <li><i class="fa fa-check"></i> Una clase presencial semanal teórico práctica de dos horas y treinta minutos (2 y 1/2).</li>
                <li><i class="fa fa-check"></i> Evaluación a la finalización del módulo.</li>
              </ul>

              <h3 class="title"><strong>Objetivos:</strong></h3>
              <ul class="list-icons font-cursos">
                <li><i class="fa fa-check"></i>Lograr a través de la instrucción electromecánica, personal capacitado, 
                    en la reparación y mantenimiento de equipos de frio familiares.</li>
              </ul>

              <h3 class="title"><strong>Temario:</strong></h3>
              <ul class="list-icons font-cursos">
                <li><i class="fa fa-check"></i>Teoría de la refrigeración.</li>
                <li><i class="fa fa-check"></i>Calor-Conducción-Radiación-Convección.</li>
                <li><i class="fa fa-check"></i>Frio-Aislamiento-Temperatura.</li>
                <li><i class="fa fa-check"></i>Escala centígrada y Fahrenheit.</li>
                <li><i class="fa fa-check"></i>Presión atmosférica y presión manométrica.</li>
                <li><i class="fa fa-check"></i>Estado de la materia- Vaporización- Congelación.</li>
                <li><i class="fa fa-check"></i>Distintos refrigerantes y lubricantes.</li>
                <li><i class="fa fa-check"></i>Circuito frigorífico según ciclos de Carnot- Componentes mecánicos.</li>
                <li><i class="fa fa-check"></i>Principio básico de heladeras familiares con congelador y freezer.</li>
                <li><i class="fa fa-check"></i>Electricidad aplicada a la refrigeración.</li>
                <li><i class="fa fa-check"></i>Ley de Ohm-Ley de Watt-Cálculos eléctricos.</li>
                <li><i class="fa fa-check"></i>Circuitos eléctricos de la era común y no frost.</li>
                <li><i class="fa fa-check"></i>Compresor eléctrico de bajo torque de arranque.</li>
                <li><i class="fa fa-check"></i>Aire acondicionando tipo Split.</li>
                <li><i class="fa fa-check"></i>Funcionamiento y reparación.</li>
                <li><i class="fa fa-check"></i>Electricidad aplicada al circuito propio del aire Split de alta potencia.</li>
                <li><i class="fa fa-check"></i>Instructivo de instalación de aire Split de la cámara argentina de aire acondicionado, 
                    calefacción y ventilación C.A.C.A.A.V.  y entrega de matrícula de Instalador de valor nacional (costo a cargo del alumno)</li>
              </ul>


              @*<a href="#" class="btn btn-animated btn-default btn-lg">External Link <i class="fa fa-external-link"></i></a>*@
              <hr>

            </div>
            <!-- main end -->

            <!-- sidebar start -->
            <!-- ================ -->
            <aside class="col-lg-4 col-xl-3 ml-xl-auto pv-40">
              <div class="sidebar">
                <div class="block clearfix font-cursos">
                  <h3 class="title">Info</h3>
                  <div class="separator-2"></div>
                  <ul class="list margin-clear">
                    <li><strong>Docente:  </strong> <span class="text-right">Juan Carlos Martínez</span></li>
                    <li><strong>Fecha de inicio:  </strong> <span class="text-right">16 de marzo de 2022</span></li>
                    <li><strong>Horarios: </strong> <span class="text-right">Turno tarde 17:00 a 19:30 / Turno noche 20 a 22:30   </span></li>
                    <li><strong>Duración: </strong> <span class="text-right">36 clases - 90 horas reloj. </span></li>
                    <li><strong>Precio: </strong> <span class="text-right">9 cuotas de $ 3900 (descuentos para alumnos UTN y empresas)</span></li>
                    
                  </ul>
                </div>
                
                
                </div>
              </div>
            </aside>
            <!-- sidebar end -->
             </div>
        </div>
      </section>

Views/Cursos/communityManager.cshtml
<section class="main-container padding-bottom-clear section pv-40 fixed-bg light-translucent-bg background-img-CM">
     <div >
        <div class="container">
          <div class="row ">

            <div class="clearfix"></div><div class="main col-lg-8 pv-40">
              <h1 class="title text-center">Community & Social Media Manager</h1>
              <div class="separator with-icon"><i class="fa fa-facebook-official bordered"></i></div>
              <p class="font-cursos">La Dirección de Capacitación y Oficios de la U.T.N. Facultad Regional San Francisco en conjunto con Espacio
                Instrumenta llevará a cabo un curso de eje de formación Tecnológica en: “Community & Social Media
                Maneger”, destinado a aquellas personas que necesitan una rápida capacitación laboral, que responda a
                las necesidades actuales del mercado, asegurándose una formación.
              </p>

              <p class="font-cursos">En estas clases aprenderás a elaborar y analizar desde otra perspectiva las redes que más le convengan a
                cada empresa o emprendimiento para el logro de sus objetivos, y una vez presentes en ellas, gestionar
                sus perfiles, armar su estrategia e interactuar con la comunidad. Todas las clases son teóricas y prácticas
                y al final de dicho curso, presentarás como trabajo final una agencia, con estrategias de contenido y
                presencia en redes.
              </p>


              <h3 class="title"><strong>Metodología:</strong></h3>
              <ul class="list-icons font-cursos">
                <li><i class="fa fa-check"></i>Clases semanales vía presencial/streaming a través de plataforma zoom.</li>
              </ul>

              <h3 class="title"><strong>Objetivos:</strong></h3>
              <ul class="list-icons font-cursos">
                <li><i class="fa fa-check"></i>Incorporar conocimientos básicos sobre el marketing digital y herramientas de publicación de
                contenido para desarrollar una estrategia a su medida.</li>
                <li><i class="fa fa-check"></i> Organizar las ideas de un emprendimiento para alinear su estrategia digital a su core business.</li>
                <li><i class="fa fa-check"></i> Desarrollar durante la formación un proyecto concreto de armado de agencia con su puesta en
                marcha real online, como instancia de aprendizaje y evaluación.</li>
                <li><i class="fa fa-check"></i> Adquirir herramientas básicas de diseño gráfico para la generación de contenidos digitales para
                redes sociales.</li>
              </ul>

              <h3 class="title"><strong>Temario:</strong></h3>
              <ul class="list-icons font-cursos">
                <li><i class="fa fa-asterisk"></i> MODULO 1:
                    <ul> 
                        <li><i ></i> Introducción al Marketing Digital: Nociones básicas. Diferencias entre marketing digital y marketing
                        tradicional. Ecosistema digital.</li>
                        <li><i ></i>Redes Sociales: Qué son y para qué sirven. Principales redes sociales en la actualidad.</li>

                    </ul>
                    </li>
                <li><i class="fa fa-asterisk"></i> MODULO 2:
                    <ul> 
                        <li><i ></i> Facebook e Instagram: Branding. Estrategias en marketing digital. Contenidos digitales.
                        Comportamiento del usuario. Copywriter.</li>
                    </ul>
                    </li>
                <li><i class="fa fa-asterisk"></i> MODULO 3:
                    <ul> 
                        <li><i ></i> Linkedin, Youtube, Tik Tok y Twitch: Estrategias en marketing digital. Contenidos digitales.
                        Comportamiento del usuario.</li>
                    </ul>
                    </li> 
                    <li><i class="fa fa-asterisk"></i> MODULO 4:
                    <ul> 
                        <li><i ></i> Diseño Gráfico: Conceptos y teorías de diseño. Aplicabilidad en la plataforma Canva. Tips de diseño
                        gráfico.</li>
                    </ul>
                    </li>   
                    <li><i class="fa fa-asterisk"></i> MODULO 5:
                    <ul> 
                        <li><i ></i> Ads: Introducción en la plataforma de Facebook e Instagram Ads. Desarrollo práctico de campañas
                        publicitarias en Facebook e Instagram. Lectura y análisis de estadísticas.</li>
                    </ul>
                    </li>   
              </ul>


              @*<a href="#" class="btn btn-animated btn-default btn-lg">External Link <i class="fa fa-external-link"></i></a>*@
              <hr>

            </div>
            <!-- main end -->

            <!-- sidebar start -->
            <!-- ================ -->
            <aside class="col-lg-4 col-xl-3 ml-xl-auto pv-40">
              <div class="sidebar">
                <div class="block clearfix font-cursos">
                  <h3 class="title">Info</h3>
                  <div class="separator-2"></div>
                  <ul class="list margin-clear">
                    <li><strong>Docente:  </strong> <span class="text-right">Noelia Etchechury</span></li>
                    <li><strong>Fecha de inicio: </strong> <span class="text-right">Febrero – Mayo y Agosto</span></li>
                    <li><strong>Horarios: </strong> <span class="text-right">18:00 a 21:00  </span></li>
                     <li><strong>Duración: </strong> <span class="text-right">4 meses </span></li>
                   
                  </ul>
                </div>
                
                
                </div>
              </div>
            </aside>
            <!-- sidebar end -->
             </div>
        </div>
      </section>